services:
    nestjs:
        container_name: nestjs
        build: ./dockers/nestjs
        ports:
            - 3000:3000
        restart: always
        networks:
            - frontend_network
            - backend_network
    mariadb:
        container_name: mariadb
        build: ./dockers/mariadb
        restart: always
        networks:
            - backend_network

networks:
    frontend_network:
        driver: bridge
    backend_network:
        driver: bridge