services:
    # nestjs:
    #     container_name: nestjs
    #     build:
    #         context: ./backend
    #         dockerfile: Dockerfile.prod
    #     ports:
    #         - 3001:3001
    #     environment:
    #         - DATABASE_URL=${DATABASE_URL}
    #         - JWT_SECRET=${JWT_SECRET}
    #         - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    #         - PORT=3001
    #     restart: always
    #     networks:
    #         - frontend_network

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/app
            - /app/node_modules
            - uploads_data:/app/uploads
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
            - PORT=3000
            - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
        restart: always
        networks:
            - frontend_network
            - backend_network
        depends_on:
            postgres:
                condition: service_healthy

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:3000
        depends_on:
            - backend
        restart: always
        networks:
            - frontend_network

    postgres:
        container_name: postgres
        image: postgres:17
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
        networks:
            - backend_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U myuser"]
            interval: 10s
            timeout: 5s
            retries: 5
    
    db-backup:
        container_name: db-backup
        image: postgres:17
        entrypoint: /bin/bash
        command: /scripts/backup.sh
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - PGPASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - backups:/backups
            - ./scripts/backup.sh:/scripts/backup.sh:ro
        networks:
            - backend_network
        depends_on:
            postgres:
                condition: service_healthy
        restart: always

networks:
    frontend_network:
        driver: bridge
    backend_network:
        driver: bridge
volumes:
  postgres_data:
  uploads_data:
  backups:
