FROM alpine:3.23

RUN apk update && apk add --no-cache \
    nodejs \
    npm \
    yarn \
    git \
    build-base \
    linux-headers

WORKDIR /usr/src/app

# Build context is ./backend — no trancendence/ prefix needed
COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:prod"]
#CMD ["sh", "-c", "tail -f /dev/null"]
