events{}

http {
	client_max_body_size 55m;

	upstream backend {
		server backend:3000;
	}

	upstream frontend {
		server frontend:5173;
	}

	server {
		listen 8080;
		return 301 https://$host:8443$request_uri;
	}

	server {
		listen 8443 ssl;

		ssl_certificate		/etc/nginx/certs/cert.pem;
		ssl_certificate_key	/etc/nginx/certs/key.pem;

		location /api/ {
			proxy_pass http://backend;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /uploads/ {
			proxy_pass http://backend;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /docs {
			proxy_pass http://backend;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /socket.io {
			proxy_pass http://backend;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
		}

		location / {
			proxy_pass http://frontend;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
		}
	}
}
