events{}

http {
	client_max_body_size 5m;

	upstream backend {
		server backend:3000;
	}

	upstream frontend {
		server frontend:5173;
	}

	server {
		listen 80;
		return 301 https://$host$request_uri;
	}

	server {
		listen 443 ssl;

		ssl_certificate		/etc/nginx/certs/cert.pem;
		ssl_certificate_key	/etc/nginx/certs/key.pem;

		location ~ ^/(auth|user|auction|item|friends|chat|health|uploads|docs|api-keys|public-api) {
			proxy_pass http://backend;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /socket.io {
			proxy_pass http://backend;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
		}

		location / {
			proxy_pass http://frontend;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
		}
	}
}
